### ISSUE TITLE
Centrifugo PRO v5.4.8 Push Notification Problem 

### ISSUE THREAD

**Issue by bigmoveus** [centrifugal/centrifugo-pro#1]
Service started.
{"level":"warn","time":"2024-12-06T20:31:54+05:30","message":"Centrifugo PRO license not found, run in sandbox mode: max connections 20, max nodes 2, max api rps 5"}
{"level":"info","version":"5.4.8","release_time":"1730871047","edition":"pro","runtime":"go1.23.2","pid":21336,"engine":"redis","gomaxprocs":16,"time":"2024-12-06T20:31:54+05:30","message":"starting Centrifugo"}
{"level":"info","owner":"unlicensed","max_connections":20,"max_nodes":2,"max_api_rps":5,"time":"2024-12-06T20:31:54+05:30","message":"license information"}
{"level":"info","path":"D:\\wamp\\www\\srplh\\servers\\cfgo\\config.json","time":"2024-12-06T20:31:54+05:30","message":"using config file"}
{"level":"info","endpoint":"https://srplh.test/cfgo/channel_events","time":"2024-12-06T20:31:54+05:30","message":"channel state proxy enabled"}
{"level":"info","endpoint":"https://srplh.test/cfgo/rpc","time":"2024-12-06T20:31:54+05:30","message":"RPC proxy enabled"}
{"level":"info","algorithms":"HS256, HS384, HS512","time":"2024-12-06T20:31:54+05:30","message":"enabled JWT verifiers"}
{"level":"info","dry_run":false,"providers":["fcm"],"queue_engine":"database","time":"2024-12-06T20:31:54+05:30","message":"push notifications providers initialized"}
{"level":"warn","time":"2024-12-06T20:31:54+05:30","message":"DEBUG mode enabled, see /debug/pprof"}
{"level":"info","time":"2024-12-06T20:31:54+05:30","message":"serving websocket, api, admin, debug endpoints on :2083"}
{"level":"error","worker-pool-id":"push-consumer-worker-a09074","worker-id":"push-consumer-worker-a09074/worker-5","job-type":"push_notifications.job","job-uid":"abee383c-4bb6-4698-bcc6-f8856a11f93d","stacktrace":"runtime error: invalid memory address or nil pointer dereference\ngoroutine 130 [running]:\ngithub.com/centrifugal/centrifugo/v5/internal/pro/gue.(*Worker).recoverPanic(0xc00179c7e0, {0x392c198, 0xc00b678270}, {0x392cd48, 0xc00b55f420}, 0xc00b62b8c0)\n\t/home/runner/work/centrifugo-pro-source/centrifugo-pro-source/internal/pro/gue/worker.go:327 +0x15e\npanic({0x2bc7700?, 0x4f0f080?})\n\t/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/panic.go:785 +0x132\ngithub.com/centrifugal/centrifugo/v5/internal/pro/analytics.(*ClickhouseTracer).TracePushNotification(0xc00b517301?, {0xc00b5611a0?, 0x21195ff?}, {0xc00b52fb6c?, 0x392c240?}, {0x3008bce?, 0xc00b55b3f0?}, {0xc0019b5ec0?, 0x1000080?}, {0xc0019b5ec0, ...}, ...)\n\t/home/runner/work/centrifugo-pro-source/centrifugo-pro-source/internal/pro/analytics/clickhouse.go:659 +0x3a\ngithub.com/centrifugal/centrifugo/v5/internal/pro/push.(*FcmSender).SendTokens(0xc0012e8e20, {0xc00b52fb6c, 0x3}, {0x3008bce, 0x6}, 0xc00249cf30, 0xc00b54b600)\n\t/home/runner/work/centrifugo-pro-source/centrifugo-pro-source/internal/pro/push/send_fcm.go:164 +0xda7\ngithub.com/centrifugal/centrifugo/v5/internal/pro/push.(*StreamProcessor).Process(0xc00036c9a0, 0xc00b507f50)\n\t/home/runner/work/centrifugo-pro-source/centrifugo-pro-source/internal/pro/push/processor.go:518 +0x21e5\ngithub.com/centrifugal/centrifugo/v5/internal/pro/push.NewPGConsumer.newProcessPG.func4({0x2bf64e0?, 0xc00178eb40?}, 0xc00b62b8c0)\n\t/home/runner/work/centrifugo-pro-source/centrifugo-pro-source/internal/pro/push/pg_consumer.go:117 +0x1e6\ngithub.com/centrifugal/centrifugo/v5/internal/pro/gue.(*Worker).WorkOne(0xc00179c7e0, {0x392c198?, 0xc001908000?})\n\t/home/runner/work/centrifugo-pro-source/centrifugo-pro-source/internal/pro/gue/worker.go:268 +0xc5f\ngithub.com/centrifugal/centrifugo/v5/internal/pro/gue.(*Worker).runLoop(0xc00179c7e0, {0x392c198, 0xc001908000})\n\t/home/runner/work/centrifugo-pro-source/centrifugo-pro-source/internal/pro/gue/worker.go:160 +0x125\ngithub.com/centrifugal/centrifugo/v5/internal/pro/gue.RunLock({0x392c198, 0xc001908000}, 0xc00131ff58, 0xc00179c828, 0xc00179c830, {0xc000d75b90, \n[...]\n","time":"2024-12-06T20:32:11+05:30","message":"Job panicked"}

 configuration.

{
  "engine": "redis",
  "port": 2083,
  "debug": true,
  "tls": true,
  "tls_key": "D:\\wamp\\bin\\Certs\\mkcert\\key.pem",
  "tls_cert": "D:\\wamp\\bin\\Certs\\mkcert\\cert.pem",
  "token_hmac_secret_key": "4aa48ee4-364f-4c2a-a161-xxxxxxxxx",
  "admin_password": "af96356b-f4a3-40e4-b05c-xxxxxxxxx",
  "admin_secret": "7972fcec-dd3f-42cf-a0ed-xxxxxxxxx",
  "api_key": "3acd865e-17d8-4a38-82b9-xxxxxxxxx",
  "allowed_origins": [
    "https://srplh.test"
  ],
  "admin": true,
  "proxy_rpc_endpoint": "https://srplh.test/cfgo/rpc",
  "proxy_rpc_timeout": "10s",
  "user_subscribe_to_personal": false,
  "user_personal_channel_namespace": "personal",
  "proxy_channel_state_endpoint": "https://srplh.test/cfgo/channel_events",
  "namespaces": [
    {
      "name": "personal",
      "presence": true,
      "channel_state_events": [
        "occupied",
        "vacated"
      ],
      "history_size": 10,
      "history_ttl": "60s",
      "force_positioning": true,
      "force_recovery": true
    },
    {
      "name": "room",
      "history_size": 10,
      "history_ttl": "60s",
      "force_positioning": true,
      "force_recovery": true
    },
    {
      "name": "all_users",
      "history_size": 10,
      "history_ttl": "60s",
      "force_positioning": true,
      "force_recovery": true
    },
    {
      "name": "visitor",
      "presence": true,
      "channel_state_events": [
        "occupied",
        "vacated"
      ],
      "history_size": 10,
      "history_ttl": "60s",
      "force_positioning": true,
      "force_recovery": true
    },
    {
      "name": "agent",
      "history_size": 10,
      "history_ttl": "60s",
      "force_positioning": true,
      "force_recovery": true
    },
    {
      "name": "all_sup_agents",
      "history_size": 10,
      "history_ttl": "60s",
      "force_positioning": true,
      "force_recovery": true
    },
    {
      "name": "sup_dept",
      "history_size": 10,
      "history_ttl": "60s",
      "force_positioning": true,
      "force_recovery": true
    }
  ],
  "user_status": {
    "enabled": false,
    "redis_address": "127.0.0.1:6379"
  },
  "database": {
    "dsn": "postgresql://postgres:xxxxxxxxx@127.0.0.1:5432/cfgo"
  },
  "push_notifications": {
     "queue_engine": "database",
    "enabled_providers": [
      "fcm"
    ],
    "fcm_credentials_file_path": "fcm.json"
  }
}

**Comment by FZambia** [comment]
Thanks for the report, I have an idea why this happens – if it's correct the fix may be shipped till the end of the week.

**Comment by FZambia** [comment]
Should be fixed in Centrifugo PRO [v5.4.9](https://github.com/centrifugal/centrifugo-pro/releases/tag/v5.4.9)
